/*
BrowserUp MitmProxy

___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 

API version: 1.27.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package BrowserUpMitmProxyClient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HarEntryRequestQueryStringInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HarEntryRequestQueryStringInner{}

// HarEntryRequestQueryStringInner struct for HarEntryRequestQueryStringInner
type HarEntryRequestQueryStringInner struct {
	Name string `json:"name"`
	Value string `json:"value"`
	Comment *string `json:"comment,omitempty"`
}

type _HarEntryRequestQueryStringInner HarEntryRequestQueryStringInner

// NewHarEntryRequestQueryStringInner instantiates a new HarEntryRequestQueryStringInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHarEntryRequestQueryStringInner(name string, value string) *HarEntryRequestQueryStringInner {
	this := HarEntryRequestQueryStringInner{}
	this.Name = name
	this.Value = value
	return &this
}

// NewHarEntryRequestQueryStringInnerWithDefaults instantiates a new HarEntryRequestQueryStringInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHarEntryRequestQueryStringInnerWithDefaults() *HarEntryRequestQueryStringInner {
	this := HarEntryRequestQueryStringInner{}
	return &this
}

// GetName returns the Name field value
func (o *HarEntryRequestQueryStringInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HarEntryRequestQueryStringInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HarEntryRequestQueryStringInner) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *HarEntryRequestQueryStringInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *HarEntryRequestQueryStringInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *HarEntryRequestQueryStringInner) SetValue(v string) {
	o.Value = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *HarEntryRequestQueryStringInner) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HarEntryRequestQueryStringInner) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *HarEntryRequestQueryStringInner) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *HarEntryRequestQueryStringInner) SetComment(v string) {
	o.Comment = &v
}

func (o HarEntryRequestQueryStringInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HarEntryRequestQueryStringInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	return toSerialize, nil
}

func (o *HarEntryRequestQueryStringInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHarEntryRequestQueryStringInner := _HarEntryRequestQueryStringInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHarEntryRequestQueryStringInner)

	if err != nil {
		return err
	}

	*o = HarEntryRequestQueryStringInner(varHarEntryRequestQueryStringInner)

	return err
}

type NullableHarEntryRequestQueryStringInner struct {
	value *HarEntryRequestQueryStringInner
	isSet bool
}

func (v NullableHarEntryRequestQueryStringInner) Get() *HarEntryRequestQueryStringInner {
	return v.value
}

func (v *NullableHarEntryRequestQueryStringInner) Set(val *HarEntryRequestQueryStringInner) {
	v.value = val
	v.isSet = true
}

func (v NullableHarEntryRequestQueryStringInner) IsSet() bool {
	return v.isSet
}

func (v *NullableHarEntryRequestQueryStringInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHarEntryRequestQueryStringInner(val *HarEntryRequestQueryStringInner) *NullableHarEntryRequestQueryStringInner {
	return &NullableHarEntryRequestQueryStringInner{value: val, isSet: true}
}

func (v NullableHarEntryRequestQueryStringInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHarEntryRequestQueryStringInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


