/*
BrowserUp MitmProxy

___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 

API version: 1.25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package BrowserUpMitmProxyClient

import (
	"encoding/json"
)

// checks if the NameValuePair type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NameValuePair{}

// NameValuePair struct for NameValuePair
type NameValuePair struct {
	// Name to match
	Name *string `json:"name,omitempty"`
	// Value to match
	Value *string `json:"value,omitempty"`
}

// NewNameValuePair instantiates a new NameValuePair object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNameValuePair() *NameValuePair {
	this := NameValuePair{}
	return &this
}

// NewNameValuePairWithDefaults instantiates a new NameValuePair object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNameValuePairWithDefaults() *NameValuePair {
	this := NameValuePair{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NameValuePair) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NameValuePair) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NameValuePair) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NameValuePair) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *NameValuePair) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NameValuePair) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *NameValuePair) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *NameValuePair) SetValue(v string) {
	o.Value = &v
}

func (o NameValuePair) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NameValuePair) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableNameValuePair struct {
	value *NameValuePair
	isSet bool
}

func (v NullableNameValuePair) Get() *NameValuePair {
	return v.value
}

func (v *NullableNameValuePair) Set(val *NameValuePair) {
	v.value = val
	v.isSet = true
}

func (v NullableNameValuePair) IsSet() bool {
	return v.isSet
}

func (v *NullableNameValuePair) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNameValuePair(val *NameValuePair) *NullableNameValuePair {
	return &NullableNameValuePair{value: val, isSet: true}
}

func (v NullableNameValuePair) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNameValuePair) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


