// <auto-generated>
/*
 * BrowserUp MitmProxy
 *
 * ___ This is the REST API for controlling the BrowserUp MitmProxy. The BrowserUp MitmProxy is a swiss army knife for automated testing that captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests. ___ 
 *
 * The version of the OpenAPI document: 1.27.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using BrowserUpMitmProxyClient.Client;

namespace BrowserUpMitmProxyClient.Model
{
    /// <summary>
    /// HarEntryRequestQueryStringInner
    /// </summary>
    public partial class HarEntryRequestQueryStringInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HarEntryRequestQueryStringInner" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="value">value</param>
        /// <param name="comment">comment</param>
        [JsonConstructor]
        public HarEntryRequestQueryStringInner(string name, string value, Option<string?> comment = default)
        {
            Name = name;
            Value = value;
            CommentOption = comment;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Used to track the state of Comment
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CommentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [JsonPropertyName("comment")]
        public string? Comment { get { return this.CommentOption; } set { this.CommentOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HarEntryRequestQueryStringInner {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HarEntryRequestQueryStringInner" />
    /// </summary>
    public class HarEntryRequestQueryStringInnerJsonConverter : JsonConverter<HarEntryRequestQueryStringInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="HarEntryRequestQueryStringInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HarEntryRequestQueryStringInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> value = default;
            Option<string?> comment = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "comment":
                            comment = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class HarEntryRequestQueryStringInner.", nameof(name));

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class HarEntryRequestQueryStringInner.", nameof(value));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class HarEntryRequestQueryStringInner.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class HarEntryRequestQueryStringInner.");

            if (comment.IsSet && comment.Value == null)
                throw new ArgumentNullException(nameof(comment), "Property is not nullable for class HarEntryRequestQueryStringInner.");

            return new HarEntryRequestQueryStringInner(name.Value!, value.Value!, comment);
        }

        /// <summary>
        /// Serializes a <see cref="HarEntryRequestQueryStringInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="harEntryRequestQueryStringInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HarEntryRequestQueryStringInner harEntryRequestQueryStringInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, harEntryRequestQueryStringInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HarEntryRequestQueryStringInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="harEntryRequestQueryStringInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HarEntryRequestQueryStringInner harEntryRequestQueryStringInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (harEntryRequestQueryStringInner.Name == null)
                throw new ArgumentNullException(nameof(harEntryRequestQueryStringInner.Name), "Property is required for class HarEntryRequestQueryStringInner.");

            if (harEntryRequestQueryStringInner.Value == null)
                throw new ArgumentNullException(nameof(harEntryRequestQueryStringInner.Value), "Property is required for class HarEntryRequestQueryStringInner.");

            if (harEntryRequestQueryStringInner.CommentOption.IsSet && harEntryRequestQueryStringInner.Comment == null)
                throw new ArgumentNullException(nameof(harEntryRequestQueryStringInner.Comment), "Property is required for class HarEntryRequestQueryStringInner.");

            writer.WriteString("name", harEntryRequestQueryStringInner.Name);

            writer.WriteString("value", harEntryRequestQueryStringInner.Value);

            if (harEntryRequestQueryStringInner.CommentOption.IsSet)
                writer.WriteString("comment", harEntryRequestQueryStringInner.Comment);
        }
    }
}
